### ISSUE TITLE
Exercise 2: Implement ToDo List

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/jQuery_JS_Evaluation#2]
https://github.com/OkwufuluezeD/jQuery_JS_Evaluation/tree/master/exercise2

On clicking + img in "ToDos sec" against each employee, add a todo input area with a save & cancel image links next to it. 

On saving, replace it with text in a div with edit & remove image links against it. 

-You can use an in-place edit plugin or can hand code it. 
- As ToDos start growing and gets more than 3 for one user, show a vertical scroll instead of occupying more vertical space(can do it through css also) 
- Try using visual effects to play it nicely. 

Clicking remove link against the todo should delete that todo. 
If all Todos for a user are removed bring back the text "Add todos of user" 

Expand all/Collapse all buttons on top of "ToDos section" as shown in the image and should expand/collapse all the Role headers with respective employee's data under them. 

There should be a Search field on the top of the page where user can put number of Todos and it should collapse all Role headers but the ones that have employees under it meeting the search criteria and flashing the employee names for few seconds(just the name on the left not todos) 

Obviously the other employees under the expanded Role header will be shown too but flashing will be done only on the ones that meet the search criteria. 

During search, lets assume that none of the todos are in edit state or new todo state. 

Note: don't keep a count of Todos stored anywhere, structure the html properly so can count todo containers under each employee. 
Negative numbers, alphabets can't be entered. 

On hovering an employee under "Employees section" a delete image link will be show on right side, clicking which a confirmation will be shown followed by removing that employee instances from all places on the page. Note: use the existing code thats already written for removing employee from "Roles sec"

**Comment by osifoanosike** [comment]
- Event delegation is meant to be an optimization measure. But in the case of https://github.com/OkwufuluezeD/jQuery_JS_Evaluation/blob/master/exercise2/js/Todo.js#L64, we can achieve an optimal code without delegation.
- https://github.com/OkwufuluezeD/jQuery_JS_Evaluation/blob/master/exercise2/js/Todo.js#L23
  method naming conventions should be improved. Method names should be verbs.

**Comment by DOkwufulueze** [comment]
Event Delegation optimized by using the data associated with each element and converting that data to the appropriate method when the element is clicked.

Naming convention properly observed.

**Comment by osifoanosike** [comment]
- Nice idea with this: https://github.com/OkwufuluezeD/jQuery_JS_Evaluation/blob/master/exercise2/js/Todo.js#L215
  However, do we still need the likes of: https://github.com/OkwufuluezeD/jQuery_JS_Evaluation/blob/master/exercise2/js/Todo.js#L207 ? 
- You can use a better naming convention: _toggleHeadExpandCollapse, _toggleRoleExpandCollapse
- this can be optimized:  https://github.com/OkwufuluezeD/jQuery_JS_Evaluation/blob/master/exercise2/js/Todo.js#L313

**Comment by DOkwufulueze** [comment]
Code Optimized and corrections implemented.

**Comment by osifoanosike** [comment]
Move your classes to separate files.

**Comment by DOkwufulueze** [comment]
All classes moved to separate files.
